[build]
jobs = 3
[profile.dev]
codegen-units = 4
# Keep it on for wasm, because of cargo bug
[target.x86_64-unknown-linux-gnu]
rustflags = ["--cap-lints=allow"]
[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

# Disable at-rest encryption, on purpose, for both release and debug builds: this
# is a dev image and we want both flavors to be able to open the same data store.
["package.engine/storage-rocksdb"]
features = []
no-default-features = true

[patch.crates-io]
nextgraph = { path = "/nextgraph-rs/sdk/rust" }
ng-sdk-python = { path = "/nextgraph-rs/sdk/python" }
ng-broker = { path = "/nextgraph-rs/engine/broker" }
ng-client-ws = { path = "/nextgraph-rs/engine/client-ws" }
ng-net = { path = "/nextgraph-rs/engine/net" }
ng-oxigraph = { path = "/nextgraph-rs/engine/oxigraph" }
ng-repo = { path = "/nextgraph-rs/engine/repo" }
ng-storage-rocksdb = { path = "/nextgraph-rs/engine/storage-rocksdb" }
ng-verifier = { path = "/nextgraph-rs/engine/verifier" }
ng-wallet = { path = "/nextgraph-rs/engine/wallet" }
ngcli = { path = "/nextgraph-rs/bin/ngcli" }
ngd = { path = "/nextgraph-rs/bin/ngd" }

# For those sources defined to track git:
[patch."https://git.nextgraph.org/rixed/async-tungstenite.git"]
ng-async-tungstenite = { path = "/async-tungstenite" }
[patch."https://git.nextgraph.org/rixed/rust-rocksdb.git"]
ng-rocksdb = { path = "/rust-rocksdb" }
